'use strict';
(()=>{
 window.FCStudioBusy=()=>Boolean(request||voiceRequest||renderRequest);
 const {$,status}=FC,editMode=new URLSearchParams(location.search).get('mode')==='edit',draftKey=editMode?'video-editor':'recap';
 const settingIds=['ratio','resolution','fit','rotate','speed','flip','brightness','contrast','saturation','sourceVolume','voiceVolume','musicVolume','captions','captionBox','font','captionColor','captionPosition','title','watermark','alignVoice'];
 let scenes=[],selected=-1,sourceBlob=null,sourceUrl='',sourceName='',narrationBlob=null,musicBlob=null,voiceById={},voiceDurations={},renderResult=null,outputUrl='',outputMap=[],sampleBlob=null,sampleUrl='',request=null,voiceRequest=null,renderRequest=null,saveTimer=null,revision=0,renderRevision=-1,undoStack=[],redoStack=[],lastSnapshot='',previewFrame=0,sourceCutoff=null;
 const player=$('sourcePlayer'),output=$('outputVideo');const id=()=>Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);
 const scene=(s={})=>({id:s.id||id(),start:0,end:10,text:'',caption:'',enabled:true,speed:1,volume:100,...s});
 function options(){const o={};for(const n of settingIds){const e=$(n);o[n]=e.type==='checkbox'?e.checked:e.type==='number'||e.type==='range'?Number(e.value):e.value}return o}
 function snapshot(){return JSON.stringify({scenes,selected,options:options(),voice:$('voice').value,voiceModel:$('voiceModel').value,sourceUrl:$('url').value,instructions:$('instructions').value})}
 function restoreMeta(p){scenes=p.scenes;selected=scenes.length?Math.max(0,Math.min(Number(p.selected)||0,scenes.length-1)):-1;for(const n of settingIds){if(p.options?.[n]===undefined)continue;const e=$(n);if(e.type==='checkbox')e.checked=!!p.options[n];else if(e.type==='number'||e.type==='range'){const v=Number(p.options[n]);if(Number.isFinite(v))e.value=String(Math.max(Number(e.min||0),Math.min(Number(e.max||10000),v)))}else if(e.tagName!=='SELECT'||[...e.options].some(x=>x.value===String(p.options[n])))e.value=String(p.options[n]).slice(0,20000)}if(p.voiceModel&&[...$('voiceModel').options].some(x=>x.value===p.voiceModel))$('voiceModel').value=p.voiceModel;if(p.voice&&[...$('voice').options].some(x=>x.value===p.voice))$('voice').value=p.voice;$('url').value=isYoutube(p.sourceUrl)?p.sourceUrl:'';$('instructions').value=String(p.instructions||'').slice(0,15000)}
 function commit(history=true){const now=snapshot();if(history&&lastSnapshot&&now!==lastSnapshot){undoStack.push(lastSnapshot);undoStack=undoStack.slice(-30);redoStack=[]}lastSnapshot=now;revision++;$('finalState').textContent=renderResult?'⚠ Project ပြောင်းထားပါတယ်။ Final ကို အသစ်ပြန်ထုတ်ပါ။':'Scene နဲ့ Output Settings ပြင်ပြီး Final ထုတ်နိုင်ပါတယ်။';$('finalState').classList.toggle('dirty',!!renderResult);clearTimeout(saveTimer);saveTimer=setTimeout(saveDraft,800);renderScenes();drawLive()}
 async function saveDraft(){try{await FC.store('put','projects',draftKey,{meta:JSON.parse(snapshot()),sourceBlob,sourceName,narrationBlob,musicBlob,voiceById,voiceDurations,at:Date.now()})}catch(e){status('editorStatus','Device Draft မသိမ်းနိုင်ပါ။ Project JSON ကို သိမ်းပြီး မူရင်းဖိုင်ကို ထိန်းထားပါ။',true)}}
 function isYoutube(url){try{const u=new URL(url);return u.protocol==='https:'&&(u.hostname==='youtu.be'||u.hostname==='youtube.com'||u.hostname.endsWith('.youtube.com'))}catch{return false}}
 function updateYoutube(){const good=isYoutube($('url').value.trim());$('youtubeOpen').classList.toggle('hide',!good);if(good)$('youtubeOpen').href=$('url').value.trim()}
 function durationOf(s){const speed=Number(s.speed||1)*Number($('speed').value);return $('alignVoice').checked&&voiceDurations[s.id]?voiceDurations[s.id]:(s.end-s.start)/speed}
 function usable(){return scenes.filter(s=>s.enabled&&s.end>s.start)}
 function validateTime(start,end){if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end<=start)throw Error('End time ဟာ Start ထက် ကြီးရပါမယ်။');if(sourceBlob&&Number.isFinite(player.duration)&&end>player.duration+.15)throw Error('End time ဟာ မူရင်း Video '+player.duration.toFixed(1)+' sec ထက် မကျော်ရပါ။')}
 function renderScenes(){const root=$('sceneEditor'),timeline=$('timeline');root.replaceChildren();timeline.replaceChildren();$('sceneCount').textContent=scenes.length+' Scenes · '+usable().reduce((n,s)=>n+durationOf(s),0).toFixed(1)+' sec';$('undo').disabled=!undoStack.length;$('redo').disabled=!redoStack.length;
  for(const [i,s] of scenes.entries()){const marker=document.createElement('button');marker.className='small'+(i===selected?' active':'');marker.textContent=(s.enabled?'':'○ ')+'Scene '+(i+1);const small=document.createElement('small');small.textContent=s.start.toFixed(1)+'–'+s.end.toFixed(1)+'s';marker.append(small);marker.onclick=()=>{selected=i;renderScenes();drawLive();loadFinalScene()};timeline.append(marker);
   const box=document.createElement('div');box.className='scene'+(i===selected?' selected':'');const head=document.createElement('div');head.className='row between';const label=document.createElement('label'),cb=document.createElement('input');cb.type='checkbox';cb.checked=s.enabled;cb.onchange=()=>{s.enabled=cb.checked;commit()};label.append(cb,document.createTextNode('Scene '+(i+1)+(voiceById[s.id]?' · 🎙':'') ));head.append(label);
   for(const [title,fn] of [['▶',()=>preview(i)],['↑',()=>move(i,-1)],['↓',()=>move(i,1)],['✕',()=>{scenes.splice(i,1);delete voiceById[s.id];delete voiceDurations[s.id];selected=Math.min(selected,scenes.length-1);commit()}]]){const b=document.createElement('button');b.className='small';b.textContent=title;b.setAttribute('aria-label',title==='✕'?'Scene ဖျက်ရန်':title==='▶'?'Scene ကြည့်ရန်':title==='↑'?'အပေါ်ရွှေ့ရန်':'အောက်ရွှေ့ရန်');b.onclick=fn;head.append(b)}if(voiceById[s.id]){const b=document.createElement('button');b.className='small';b.textContent='Scene Voice ဖယ်';b.onclick=()=>{delete voiceById[s.id];delete voiceDurations[s.id];commit()};head.append(b)}box.append(head);
   const grid=document.createElement('div');grid.className='grid';for(const [prop,title] of [['start','Start (sec)'],['end','End (sec)']]){const l=document.createElement('label');l.textContent=title;const v=document.createElement('input');v.type='number';v.min='0';v.step='.1';v.value=s[prop].toFixed(2);v.onchange=()=>{try{const start=prop==='start'?Number(v.value):s.start,end=prop==='end'?Number(v.value):s.end;validateTime(start,end);s[prop]=Number(v.value);commit()}catch(e){v.value=s[prop];status('editorStatus',FC.error(e),true)}};l.append(v);grid.append(l)}box.append(grid);
   for(const [prop,title] of [['text','Narration — ဇာတ်လမ်းပြောစာသား'],['caption','Subtitle — ပုံပေါ်က စာသား']]){const l=document.createElement('label');l.textContent=title;const t=document.createElement('textarea');t.value=s[prop];t.setAttribute('aria-label','Scene '+(i+1)+' '+prop);t.onchange=()=>{if(prop==='text'&&s.text!==t.value){delete voiceById[s.id];delete voiceDurations[s.id]}s[prop]=t.value.slice(0,20000);commit()};l.append(t);box.append(l)}
   const l=document.createElement('label');l.textContent='Scene Speed';const speed=document.createElement('select');for(const n of [.5,.75,1,1.25,1.5,2]){const o=document.createElement('option');o.value=n;o.textContent=n+'×';speed.append(o)}speed.value=String(s.speed);speed.onchange=()=>{s.speed=Number(speed.value);commit()};l.append(speed);box.append(l);const vl=document.createElement('label');vl.textContent='Scene မူရင်းအသံ %';const volume=document.createElement('input');volume.type='number';volume.min='0';volume.max='100';volume.value=s.volume;volume.onchange=()=>{s.volume=Math.max(0,Math.min(100,Number(volume.value)||0));commit()};vl.append(volume);box.append(vl);root.append(box)
  }
  if(document.activeElement!==$('fullScript'))$('fullScript').value=scenes.map(s=>s.text).join('\n');const fs=$('finalScene');fs.replaceChildren();scenes.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent='Scene '+(i+1);fs.append(o)});if(selected>=0)fs.value=selected;
 }
 function move(i,d){const n=i+d;if(n<0||n>=scenes.length)return;[scenes[i],scenes[n]]=[scenes[n],scenes[i]];selected=n;commit()}
 function drawLive(){if(!sourceBlob||!player.videoWidth)return;const c=$('editCanvas'),o=options();c.width=o.ratio==='9:16'?360:o.ratio==='1:1'?540:640;c.height=o.ratio==='9:16'?640:o.ratio==='1:1'?540:360;const s=scenes[selected]||scene({end:player.duration});FCRender.draw(c.getContext('2d'),player,o,s,Math.max(0,Math.min(1,(player.currentTime-s.start)/(s.end-s.start))));c.classList.remove('hide')}
 function animate(){cancelAnimationFrame(previewFrame);drawLive();if(!player.paused)previewFrame=requestAnimationFrame(animate)}player.addEventListener('play',animate);player.addEventListener('seeked',drawLive);player.addEventListener('pause',drawLive);
 function stopPreview(){player.pause();if(sourceCutoff){player.removeEventListener('timeupdate',sourceCutoff);sourceCutoff=null}cancelAnimationFrame(previewFrame)}
 async function preview(i=selected){try{const s=scenes[i];if(!sourceBlob||!s)throw Error('Scene Preview အတွက် မူရင်း Video ဖိုင် တင်ပါ။');stopPreview();selected=i;renderScenes();validateTime(s.start,s.end);await FCRender.seek(player,s.start);player.playbackRate=Number(s.speed)*Number($('speed').value);player.muted=Number($('sourceVolume').value)===0;sourceCutoff=()=>{if(player.currentTime>=s.end)stopPreview()};player.addEventListener('timeupdate',sourceCutoff);await player.play();status('sourceStatus','Scene '+(i+1)+' Preview ကြည့်နေပါတယ်။');$('sourcePanel').scrollIntoView({behavior:'smooth'})}catch(e){status('sourceStatus',FC.error(e),true)}}
 async function attach(blob,name,create=true){stopPreview();if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceBlob=blob;sourceName=name;sourceUrl=URL.createObjectURL(blob);player.src=sourceUrl;player.classList.remove('hide');await FC.metadata(player);$('sourceInfo').textContent=name+' · '+player.duration.toFixed(2)+' sec · '+player.videoWidth+'×'+player.videoHeight;if(create&&!scenes.length){scenes=[scene({end:player.duration})];selected=0}if(player.readyState<2)await new Promise((r,j)=>{const t=setTimeout(()=>j(Error('Video decode စောင့်ဆိုင်းမှု ရပ်ပါပြီ။')),15000);player.addEventListener('loadeddata',()=>{clearTimeout(t);r()},{once:true})});drawLive();status('sourceStatus','✓ မူရင်း Video အဆင်သင့်ပါ။ Scene ပြင်နိုင်ပါတယ်။')}
 $('file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(!FC.mime(f).startsWith('video/'))throw Error('Video ဖိုင် ရွေးပါ။');await attach(f,f.name);commit()}catch(e){status('sourceStatus',FC.error(e),true)}finally{e.target.value=''}};
 $('url').onchange=()=>{updateYoutube();commit()};$('previewScene').onclick=()=>preview();$('stopPreview').onclick=stopPreview;
 $('addScene').onclick=()=>{const start=scenes[selected]?.end||0,end=sourceBlob?Math.min(start+10,player.duration):start+10;if(end<=start)return status('editorStatus','Source အဆုံး ရောက်နေပါတယ်။ Scene time ကို ပြင်ပြီးမှ ထပ်ထည့်ပါ။',true);scenes.push(scene({start,end}));selected=scenes.length-1;commit()};$('splitScene').onclick=()=>{const s=scenes[selected],t=player.currentTime;if(!s||!sourceBlob||t<=s.start+.1||t>=s.end-.1)return status('editorStatus','မူရင်း Player ကို Scene အလယ်မှာ ရပ်ပြီး ခွဲပါ။',true);const second=scene({...s,id:id(),start:t,text:'',caption:''});s.end=t;delete voiceById[s.id];delete voiceDurations[s.id];scenes.splice(selected+1,0,second);commit()};
 $('undo').onclick=()=>{if(!undoStack.length)return;redoStack.push(snapshot());restoreMeta(JSON.parse(undoStack.pop()));lastSnapshot=snapshot();commit(false)};$('redo').onclick=()=>{if(!redoStack.length)return;undoStack.push(snapshot());restoreMeta(JSON.parse(redoStack.pop()));lastSnapshot=snapshot();commit(false)};
 $('applyScript').onclick=()=>{const words=$('fullScript').value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(!words.length)return status('editorStatus','ဇာတ်လမ်းပြောစာသား ထည့်ပါ။',true);const chosen=words.slice(0,120),span=sourceBlob?player.duration/chosen.length:10;scenes=chosen.map((text,i)=>scene({start:i*span,end:(i+1)*span,text,caption:text}));selected=0;voiceById={};voiceDurations={};commit()};
 for(const n of settingIds)$(n).addEventListener('change',()=>{const e=$(n);if(e.type==='number'){const lo=Number(e.min||0),hi=Number(e.max||10000);e.value=Math.max(lo,Math.min(hi,Number(e.value)||lo))}commit()});
 $('showKey').onclick=()=>$('key').type=$('key').type==='password'?'text':'password';$('testKey').onclick=async()=>{const b=$('testKey');b.disabled=true;try{await FC.models($('key').value,[['model','text'],['voiceModel','voice']])}catch(e){status('keyStatus',FC.error(e),true)}finally{b.disabled=false}};
 async function analysis(edit=false){if(request)return;const key=$('key').value.trim();if(!key)return status('analysisStatus','AI သုံးဖို့ API Key ထည့်ပါ။ Manual Scene Editor ကို API မပါဘဲ သုံးနိုင်ပါတယ်။',true);if(edit&&!$('instructions').value.trim())return status('analysisStatus','ဘာတွေ ပြင်ချင်သလဲ ညွှန်ကြားချက် ဖြည့်ပါ။',true);if(!sourceBlob&&!isYoutube($('url').value.trim()))return status('analysisStatus','မူရင်း Video ဖိုင် သို့မဟုတ် Public YouTube Link ထည့်ပါ။',true);request=new AbortController();$('generate').disabled=true;$('aiEdit').disabled=true;$('cancelAI').classList.remove('hide');let cleanup=async()=>{};try{status('analysisStatus','AI က Video လေ့လာနေပါတယ်…');let videoPart;if(sourceBlob){const upload=await FC.videoInput(key,sourceBlob,request.signal,s=>status('analysisStatus',s));videoPart=upload.part;cleanup=upload.cleanup}else videoPart={fileData:{fileUri:$('url').value.trim(),mimeType:'video/mp4'}};const prompt=(edit?'Plan an edit according to the requested changes.':'Watch the actual visual and audible events. Write a faithful movie recap in natural spoken Burmese. Do not invent characters or events. Do not quote long original dialogue.')+' Target narration length: '+$('duration').value+' seconds. Style: '+$('style').value+'. Owner instructions: '+$('instructions').value+'. '+(sourceBlob?'Source duration is '+player.duration+' seconds. ':'')+'Return strict JSON only: {"scenes":[{"start_ms":0,"end_ms":10000,"narration":"Burmese narration","caption":"Burmese subtitle"}]}. Choose 1 to 80 chronological relevant source segments. All timestamps are SOURCE positions in milliseconds. Every end must exceed start; stay within the actual source duration.';const j=await FC.api(key,'models/'+encodeURIComponent($('model').value)+':generateContent',{contents:[{role:'user',parts:[{text:prompt},videoPart]}],generationConfig:{responseMimeType:'application/json'}},{signal:request.signal,timeout:240000});const data=FC.json(FC.text(j));if(!Array.isArray(data.scenes))throw Error('AI Scene JSON မရပါ။ Manual Editor ကို ဆက်သုံးနိုင်ပါတယ်။');const next=data.scenes.slice(0,120).map(s=>scene({start:Number(s.start_ms)/1000,end:Number(s.end_ms)/1000,text:String(s.narration||'').slice(0,15000),caption:String(s.caption??s.narration??'').slice(0,15000)})).filter(s=>Number.isFinite(s.start)&&Number.isFinite(s.end)&&s.start>=0&&s.end>s.start&&(!sourceBlob||s.end<=player.duration+.15));if(!next.length)throw Error('အသုံးပြုနိုင်တဲ့ Scene မရပါ။ AI output time / source ကို စစ်ပါ။');scenes=next;selected=0;voiceById={};voiceDurations={};commit();status('analysisStatus','✓ Scene '+scenes.length+' ခု ရပါပြီ။ အချိန်နဲ့ ဇာတ်လမ်းကို စစ်ပြီး ပြင်ပါ။');$('editorPanel').scrollIntoView({behavior:'smooth'})}catch(e){status('analysisStatus',FC.error(e),true)}finally{await cleanup();request=null;$('generate').disabled=false;$('aiEdit').disabled=false;$('cancelAI').classList.add('hide')}}
 $('generate').onclick=()=>analysis();$('aiEdit').onclick=()=>analysis(true);$('cancelAI').onclick=()=>request?.abort();
 async function makeVoice(all=false,sample=false){if(voiceRequest)return;const list=sample?[{id:'sample',text:$('sampleText').value.trim()}]:(all?usable():[scenes[selected]]).filter(s=>s?.text.trim());if(!list.length)return status('voiceStatus','Narration စာသား အရင်ထည့်ပါ။',true);if(!sample&&all&&Object.keys(voiceById).length&& !confirm('Scenes အားလုံးအတွက် AI Voice အသစ်ထုတ်မလား? Google usage ကုန်နိုင်ပါတယ်။'))return;voiceRequest=new AbortController();$('cancelVoice').classList.remove('hide');for(const n of ['sampleVoice','generateVoice','generateAllVoice'])$(n).disabled=true;try{for(const [i,s] of list.entries()){status('voiceStatus','Voice '+(i+1)+' / '+list.length+' ထုတ်နေပါတယ်…');const b=await FC.voice($('key').value,$('voiceModel').value,s.text,$('voice').value,$('voiceStyle').value,voiceRequest.signal);sampleBlob=b;if(!sample){voiceById[s.id]=b;const ac=new (window.AudioContext||window.webkitAudioContext)();try{voiceDurations[s.id]=(await ac.decodeAudioData(await b.arrayBuffer())).duration}finally{await ac.close()}}}if(sampleUrl)URL.revokeObjectURL(sampleUrl);sampleUrl=URL.createObjectURL(sampleBlob);$('voicePreview').src=sampleUrl;$('voicePreview').classList.remove('hide');if(sample)$('voicePreview').play().catch(()=>{});if(!sample)commit();status('voiceStatus','✓ အသံရပါပြီ။ နားထောင်စစ်ပြီး Final ပြန်ထုတ်ပါ။')}catch(e){status('voiceStatus',FC.error(e),true)}finally{voiceRequest=null;$('cancelVoice').classList.add('hide');for(const n of ['sampleVoice','generateVoice','generateAllVoice'])$(n).disabled=false}}
 $('sampleVoice').onclick=()=>makeVoice(false,true);$('generateVoice').onclick=()=>makeVoice();$('generateAllVoice').onclick=()=>makeVoice(true);$('cancelVoice').onclick=()=>voiceRequest?.abort();$('saveVoice').onclick=async()=>{try{const b=voiceById[scenes[selected]?.id]||sampleBlob;status('voiceStatus',await FC.save(b,'FutureCode_Scene_Voice.wav'))}catch(e){status('voiceStatus',FC.error(e),true)}};
 for(const [input,kind] of [['narrationFile','narration'],['musicFile','music']])$(input).onchange=e=>{const f=e.target.files[0];if(!f)return;if(!FC.mime(f).startsWith('audio/'))return status('voiceStatus','Audio ဖိုင် ရွေးပါ။',true);if(kind==='narration')narrationBlob=f;else musicBlob=f;$('audioInfo').textContent=(narrationBlob?'Narration: '+(narrationBlob.name||'Audio')+' · ':'')+(musicBlob?'Music: '+(musicBlob.name||'Audio'):'');commit();e.target.value=''};
 $('removeNarration').onclick=()=>{narrationBlob=null;$('audioInfo').textContent='Uploaded narration ဖယ်ပြီးပါပြီ။';commit()};$('removeMusic').onclick=()=>{musicBlob=null;$('audioInfo').textContent='Music ဖယ်ပြီးပါပြီ။';commit()};
 function loadFinalScene(){const s=scenes[Number($('finalScene').value)];if(!s)return;$('finalStart').value=s.start.toFixed(2);$('finalEnd').value=s.end.toFixed(2);$('finalNarration').value=s.text;$('finalCaption').value=s.caption;$('finalSpeed').value=s.speed}
 $('finalScene').onchange=()=>{selected=Number($('finalScene').value);loadFinalScene()};$('editFinal').onclick=()=>{if(!scenes.length)return status('renderStatus','Scene အရင်ထည့်ပါ။',true);if(renderResult){let at=0;for(const m of outputMap){if(output.currentTime<at+m.duration){const i=scenes.findIndex(s=>s.id===m.id);if(i>=0)selected=i;break}at+=m.duration}}output.pause();if(selected<0)selected=0;$('finalScene').value=selected;$('finalEditor').classList.remove('hide');loadFinalScene()};
 $('applyFinalEdit').onclick=()=>{try{const i=Number($('finalScene').value),s=scenes[i];if(!s)throw Error('Scene ရွေးပါ။');const start=Number($('finalStart').value),end=Number($('finalEnd').value);validateTime(start,end);if(s.text!==$('finalNarration').value){delete voiceById[s.id];delete voiceDurations[s.id]}Object.assign(s,{start,end,text:$('finalNarration').value.slice(0,20000),caption:$('finalCaption').value.slice(0,20000),speed:Number($('finalSpeed').value)});selected=i;commit();status('renderStatus','✓ ပြင်ဆင်ချက် ထည့်ပြီးပါပြီ။ Final Video ပြန်ထုတ်မည်ကို နှိပ်ပါ။')}catch(e){status('renderStatus',FC.error(e),true)}};
 $('render').onclick=async()=>{if(renderRequest)return;if(!sourceBlob)return status('renderStatus','Final ထုတ်ဖို့ မူရင်း Video ဖိုင် တင်ပါ။',true);const list=usable();if(!list.length)return status('renderStatus','Enabled Scene အရင်ထည့်ပါ။',true);renderRequest=new AbortController();$('render').disabled=true;$('cancelRender').classList.remove('hide');stopPreview();const version=revision;const editable=[...document.querySelectorAll('input,select,textarea,button')].filter(e=>e.id!=='cancelRender');const before=editable.map(e=>e.disabled);editable.forEach(e=>e.disabled=true);try{status('renderStatus','Export စတင်နေပါတယ်…');const result=await FCRender.render(player,list,options(),{voiceById,narrationBlob,musicBlob,signal:renderRequest.signal,progress:p=>{$('renderBar').value=p.percent;status('renderStatus','Scene '+p.scene+'/'+p.count+' · '+p.percent+'% · '+p.seconds.toFixed(1)+' / '+p.total.toFixed(1)+' sec')}});renderResult=result;renderRevision=version;outputMap=list.map((s,i)=>({id:s.id,duration:result.durations[i].duration}));if(outputUrl)URL.revokeObjectURL(outputUrl);outputUrl=URL.createObjectURL(result.blob);output.src=outputUrl;output.classList.remove('hide');$('saveVideo').disabled=false;$('finalState').textContent='✓ Final အဆင်သင့် · '+result.extension.toUpperCase()+' · '+result.duration.toFixed(1)+' sec';$('finalState').classList.remove('dirty');status('renderStatus','✓ Final Preview ကြည့်ပြီး ဒီနေရာကနေ ပြန်ပြင်နိုင်၊ သိမ်းနိုင်ပါတယ်။');await saveDraft()}catch(e){status('renderStatus',FC.error(e),true)}finally{editable.forEach((e,i)=>e.disabled=before[i]);$('render').disabled=false;$('saveVideo').disabled=!renderResult;$('cancelRender').classList.add('hide');renderRequest=null;renderScenes()}};
 $('cancelRender').onclick=()=>renderRequest?.abort();$('saveVideo').onclick=async()=>{try{if(!renderResult)throw Error('Final အရင်ထုတ်ပါ။');if(renderRevision!==revision&&!confirm('ပြင်ဆင်ချက်အသစ် မပါသေးတဲ့ အရင် Final ကို သိမ်းမလား?'))return;status('renderStatus',await FC.save(renderResult.blob,'FutureCode_Final_'+Date.now()+'.'+renderResult.extension))}catch(e){status('renderStatus',FC.error(e),true)}};
 function fmt(sec){const ms=Math.round(Math.max(0,sec)*1000),s=Math.floor(ms/1000);return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(n=>String(n).padStart(2,'0')).join(':')+','+String(ms%1000).padStart(3,'0')}
 $('exportSrt').onclick=async()=>{try{const list=usable();if(!list.length)throw Error('Scenes အရင်ထည့်ပါ။');let at=0,n=0,body='';for(const s of list){const d=durationOf(s);if(s.caption.trim())body+=(++n)+'\n'+fmt(at)+' --> '+fmt(at+d)+'\n'+s.caption+'\n\n';at+=d}if(!body)throw Error('Subtitle စာသား ထည့်ပါ။');status('editorStatus',await FC.save(new Blob([body],{type:'text/plain;charset=utf-8'}),'FutureCode_Subtitles.srt'))}catch(e){status('editorStatus',FC.error(e),true)}};
 $('saveProject').onclick=async()=>{try{const meta=JSON.parse(snapshot());meta.sourceFile=sourceName;status('editorStatus',await FC.save(new Blob([JSON.stringify({schema:'future-code-video-v7',...meta},null,2)],{type:'application/json'}),'FutureCode_Edit_Project.json'))}catch(e){status('editorStatus',FC.error(e),true)}};
 function validateProject(p){if(!['future-code-video-v7','future-code-recap-v6'].includes(p.schema)||!Array.isArray(p.scenes))throw Error('Future Code Project JSON မဟုတ်ပါ။');const old=p.schema==='future-code-recap-v6';const imported=p.scenes.slice(0,120).map(s=>scene({start:Number(s.start)/(old?1000:1),end:Number(s.end)/(old?1000:1),text:String(s.text||'').slice(0,20000),caption:String(s.caption??s.text??'').slice(0,20000),enabled:s.enabled!==false,volume:Math.max(0,Math.min(100,Number(s.volume??100)||0)),speed:[.5,.75,1,1.25,1.5,2].includes(Number(s.speed))?Number(s.speed):1})).filter(s=>Number.isFinite(s.start)&&Number.isFinite(s.end)&&s.start>=0&&s.end>s.start);return {...p,scenes:imported,selected:0}}
 $('loadProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>3*1048576)throw Error('Project JSON 3 MB အောက် ရွေးပါ။');const p=validateProject(JSON.parse(await f.text()));restoreMeta(p);voiceById={};voiceDurations={};commit();updateYoutube();status('editorStatus','✓ Project ဖွင့်ပြီးပါပြီ။ မူရင်းဖိုင် '+(p.sourceFile||'')+' ကို လိုအပ်ရင် ပြန်တင်ပါ။')}catch(e){status('editorStatus',FC.error(e),true)}finally{e.target.value=''}};
 $('restoreDraft').onclick=async()=>{try{const d=await FC.store('get','projects',draftKey);if(!d?.meta)throw Error('Device Draft မရှိသေးပါ။');restoreMeta(d.meta);voiceById=d.voiceById||{};voiceDurations=d.voiceDurations||{};narrationBlob=d.narrationBlob;musicBlob=d.musicBlob;if(d.sourceBlob)await attach(d.sourceBlob,d.sourceName||'Draft video',false);commit();updateYoutube();status('editorStatus','✓ Device Draft ပြန်ဖွင့်ပြီးပါပြီ။')}catch(e){status('editorStatus',FC.error(e),true)}};
 for(const b of document.querySelectorAll('[data-jump]'))b.onclick=()=>$(b.dataset.jump).scrollIntoView({behavior:'smooth',block:'start'});
 if(editMode){$('pageTitle').textContent='Future Code Video Editor';$('youtubeFields').classList.add('hide');$('sourceVolume').value='100';$('generate').textContent='✦ Video ကို AI နဲ့ Scenes ခွဲမည်'}
 async function init(){try{const h=await FC.store('get','handoff','video');if(h&&Date.now()-h.at<3600000&&editMode){await attach(h.blob,h.details.name||'Generated Video');if(h.details.instructions)$('instructions').value=h.details.instructions;if(h.details.narration){scenes[0].text=h.details.narration;scenes[0].caption=h.details.narration}await FC.store('delete','handoff','video');commit()}}catch(e){status('sourceStatus',FC.error(e),true)}lastSnapshot=snapshot();renderScenes();updateYoutube()}init();
 window.FCEditor={getScenes:()=>scenes,getOptions:options,getRevision:()=>revision};
})();
