'use strict';
window.FC=(()=>{
 const BASE='https://generativelanguage.googleapis.com/v1beta/';
 const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms));
 function status(id,text,bad=false){const e=$(id);if(e){e.textContent=text;e.classList.toggle('bad',bad)}}
 function error(e){const m=String(e?.message||e);if(e?.name==='AbortError')return 'လုပ်ဆောင်မှု ရပ်ထားပါပြီ။ ပို့ပြီးသား AI request ကို Google က ဆက်လုပ်နေနိုင်ပါတယ်။';if(/429|quota|RESOURCE_EXHAUSTED/i.test(m))return 'Google API quota ပြည့်နေပါတယ်။ AI Studio မှာ quota စစ်ပြီးမှ ပြန်စမ်းပါ။ '+m;if(/401|API_KEY_INVALID|API key not valid/i.test(m))return 'API Key မမှန်ပါ။ Google AI Studio မှာ key စစ်ပါ။';if(/403|PERMISSION_DENIED|billing/i.test(m))return 'ဒီ model အတွက် API access / region / billing ကို စစ်ပါ။ '+m;if(/404|NOT_FOUND/i.test(m))return 'ရွေးထားတဲ့ model သို့မဟုတ် ဖိုင် မရနိုင်ပါ။ Key Test နဲ့ model စာရင်း အသစ်ယူပါ။ '+m;if(/Failed to fetch|NetworkError|CORS/i.test(m))return 'အင်တာနက် / VPN / Google API ချိတ်ဆက်မှု မရပါ။ ချိတ်ဆက်မှု စစ်ပြီးမှ ပြန်စမ်းပါ။';return m.slice(0,900)}
 async function api(key,path,payload=null,{signal,timeout=180000,method=payload===null?'GET':'POST'}={}){
  if(!key?.trim())throw Error('Google Gemini API Key ထည့်ပါ။');
  if(!/^[a-zA-Z0-9._:/?&=%+\-]+$/.test(path)||path.includes('..')||path.startsWith('http'))throw Error('API resource မမှန်ပါ။');
  const controller=new AbortController(),abort=()=>controller.abort(signal?.reason);if(signal?.aborted)abort();signal?.addEventListener('abort',abort,{once:true});let timed=false;const timer=setTimeout(()=>{timed=true;controller.abort()},timeout);
  try{const res=await fetch(BASE+path,{method,headers:{'x-goog-api-key':key.trim(),...(payload===null?{}:{'Content-Type':'application/json'})},signal:controller.signal,...(payload===null?{}:{body:JSON.stringify(payload)})});const j=await res.json().catch(()=>null);if(!res.ok)throw Error('HTTP '+res.status+': '+(j?.error?.message||'Google API error'));if(!j&&method==='DELETE')return {};if(!j)throw Error('Google API response JSON မမှန်ပါ။');return j}catch(e){if(timed)throw Error('အချိန်ကြာလွန်းလို့ စောင့်ဆိုင်းမှု ရပ်လိုက်ပါတယ်။ Request ကို အလိုအလျောက် ပြန်မပို့ပါ။');throw e}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort)}
 }
 function parts(j){if(j.promptFeedback?.blockReason)throw Error('Google safety: '+j.promptFeedback.blockReason);const p=j.candidates?.[0]?.content?.parts;if(!p?.length)throw Error('AI output မပါပါ။ '+(j.candidates?.[0]?.finishReason||'Model / quota ကိုစစ်ပါ။'));return p}
 const text=j=>parts(j).filter(p=>p.text).map(p=>p.text).join('\n');
 function json(t){const clean=t.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,'').trim();return JSON.parse(clean.slice(clean.indexOf('{'),clean.lastIndexOf('}')+1))}
 async function models(key,selectors,statusId='keyStatus'){
  let all=[],page='';for(let i=0;i<8;i++){const j=await api(key,'models?pageSize=1000'+(page?'&pageToken='+encodeURIComponent(page):''));all.push(...(j.models||[]));page=j.nextPageToken;if(!page)break}
  for(const [id,kind] of selectors){const s=$(id);if(!s)continue;const current=s.value;const list=all.filter(m=>{const n=m.name||'';return kind==='image'?/image|nano-banana/i.test(n)&&!/(embedding|imagen)/i.test(n):kind==='video'?/veo-/.test(n):kind==='voice'?/tts/.test(n):/gemini/.test(n)&&!/(tts|image|embedding|audio|live|robot|deep-research)/i.test(n)&&(m.supportedGenerationMethods||[]).includes('generateContent')});if(list.length){s.replaceChildren();for(const m of list){const o=document.createElement('option');o.value=m.name.replace(/^models\//,'');o.textContent=m.displayName||o.value;s.append(o)}if([...s.options].some(o=>o.value===current))s.value=current;else s.selectedIndex=0}}
  status(statusId,'✓ API Key ကို Google က လက်ခံပါတယ်။ ရနိုင်တဲ့ model စာရင်း အသစ်ယူပြီးပါပြီ။ Generate လုပ်ချိန်မှာ သီးခြား quota / billing လိုနိုင်ပါတယ်။');return all
 }
 const base64=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('ဖိုင်ကို ဖတ်မရပါ။'));r.readAsDataURL(blob)});
 function mime(file){if(file.type)return file.type;const x=file.name?.split('.').pop()?.toLowerCase();return ({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',mp4:'video/mp4',webm:'video/webm',mov:'video/quicktime',wav:'audio/wav',mp3:'audio/mpeg',m4a:'audio/mp4'})[x]||''}
 async function imagePart(file){const type=mime(file);if(!['image/png','image/jpeg','image/webp'].includes(type))throw Error('PNG / JPG / WEBP ပုံကို ရွေးပါ။');if(file.size>20*1048576)throw Error('Reference ပုံ တစ်ပုံ 20 MB အောက် ဖြစ်ရပါမယ်။');const u=URL.createObjectURL(file);try{const img=new Image();img.src=u;await new Promise((r,j)=>{img.onload=r;img.onerror=()=>j(Error('ပုံကို ဖွင့်မရပါ။'))});const scale=Math.min(1,2048/Math.max(img.naturalWidth,img.naturalHeight));if(scale===1&&file.size<=5*1048576)return {inlineData:{mimeType:type,data:await base64(file)}};const c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const b=await new Promise(r=>c.toBlob(r,type==='image/png'?'image/png':'image/jpeg',.9));if(!b)throw Error('Reference ပုံကို ပြင်ဆင်မရပါ။');return {inlineData:{mimeType:b.type,data:await base64(b)}}}finally{URL.revokeObjectURL(u)}}
 const from64=(data,type)=>new Blob([Uint8Array.from(atob(data),c=>c.charCodeAt(0))],{type});
 async function save(blob,name){if(!blob?.size)throw Error('သိမ်းဖို့ ဖိုင် မရှိသေးပါ။');const bridge=window.FutureCodeDownloads;if(bridge&&typeof bridge.beginSave==='function'){const id=bridge.beginSave(name,blob.type.split(';')[0]||'application/octet-stream');if(!id)throw Error('အခြားဖိုင်ကို သိမ်းနေပါတယ်။ အရင် Save ကို အပြီးလုပ်ပါ။');try{for(let start=0;start<blob.size;start+=393216){const chunk=await base64(blob.slice(start,start+393216));if(!bridge.appendSave(id,chunk))throw Error('ဖိုင် သိမ်းဆည်းမှု ပြတ်တောက်သွားပါတယ်။');await sleep(0)}if(!bridge.finishSave(id))throw Error("Save dialog မစတင်နိုင်ပါ။");return 'ဖိုင်သိမ်းမယ့် နေရာရွေးပြီး Save နှိပ်ပါ။'}catch(e){bridge.cancelSave(id);throw e}}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);return 'Download စတင်ပြီးပါပြီ။'}
 async function copy(t){try{await navigator.clipboard.writeText(t)}catch{const a=document.createElement('textarea');a.value=t;document.body.append(a);a.select();if(!document.execCommand('copy')){a.remove();throw Error('စာသားကို ရွေးပြီး Copy လုပ်ပါ။')}a.remove()}}
 let dbPromise;function db(){if(!dbPromise)dbPromise=new Promise((r,j)=>{const q=indexedDB.open('future_code_studio_v7',1);q.onupgradeneeded=()=>{for(const n of ['projects','images','handoff'])q.result.createObjectStore(n)};q.onsuccess=()=>r(q.result);q.onerror=()=>{dbPromise=null;j(q.error)}});return dbPromise}
 async function store(action,table,key,value){const d=await db();return new Promise((r,j)=>{const t=d.transaction(table,action==='get'||action==='all'?'readonly':'readwrite'),s=t.objectStore(table);let q;if(action==='get')q=s.get(key);else if(action==='all')q=s.getAll();else if(action==='put')q=s.put(value,key);else if(action==='delete')q=s.delete(key);else q=s.clear();t.oncomplete=()=>r(q.result);t.onerror=()=>j(t.error);t.onabort=()=>j(t.error||Error('Device storage unavailable'))})}
 function audioWav(bytes,rate=24000){if(bytes.length>=12&&String.fromCharCode(...bytes.slice(0,4))==='RIFF')return new Blob([bytes],{type:'audio/wav'});const b=new ArrayBuffer(44+bytes.length),v=new DataView(b);for(const [off,t] of [[0,'RIFF'],[8,'WAVE'],[12,'fmt '],[36,'data']])for(let i=0;i<t.length;i++)v.setUint8(off+i,t.charCodeAt(i));v.setUint32(4,36+bytes.length,true);v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);v.setUint32(40,bytes.length,true);new Uint8Array(b,44).set(bytes);return new Blob([b],{type:'audio/wav'})}
 async function voice(key,model,words,name,style,signal){const newer=/gemini-3\.8/.test(model);const j=await api(key,'models/'+encodeURIComponent(model)+':generateContent',{contents:[{role:'user',parts:[{text:newer?words:'Read the following text in natural Burmese. '+style+'\n'+words,...(newer?{speech_metadata:{style}}:{})}]}],generationConfig:{responseModalities:['AUDIO'],speechConfig:{voiceConfig:newer?{voice:name}:{prebuiltVoiceConfig:{voiceName:name}}}}},{signal});const p=parts(j).find(x=>x.inlineData?.data);if(!p)throw Error('AI အသံ မပါပါ။ Voice model ကို စစ်ပါ။');const bytes=Uint8Array.from(atob(p.inlineData.data),c=>c.charCodeAt(0));return audioWav(bytes,Number(/rate=(\d+)/.exec(p.inlineData.mimeType||'')?.[1]||24000))}
 async function metadata(video){if(video.readyState>=1&&Number.isFinite(video.duration)&&video.duration>0)return;await new Promise((r,j)=>{const t=setTimeout(()=>done(Error('Video ကို ဖွင့်ဖို့ အချိန်ကြာနေပါတယ်။ ဖိုင် format စစ်ပါ။')),18000);function done(e){clearTimeout(t);video.removeEventListener('loadedmetadata',ok);video.removeEventListener('error',bad);e?j(e):r()}const ok=()=>done(Number.isFinite(video.duration)&&video.duration>0?null:Error('Video ကြာချိန် ဖတ်မရပါ။')),bad=()=>done(Error('ဖုန်းက ဒီ Video codec ကို ဖွင့်မရပါ။ MP4 / WebM ကို စမ်းပါ။'));video.addEventListener('loadedmetadata',ok);video.addEventListener('error',bad)})}
 async function videoInput(key,file,signal,progress){if(!mime(file).startsWith('video/'))throw Error('Video ဖိုင် ရွေးပါ။');if(file.size>500*1048576)throw Error('AI Analysis ဖိုင်ကို 500 MB အောက် clip ခွဲပြီး တင်ပါ။');if(file.size<=12*1048576)return {part:{inlineData:{mimeType:mime(file),data:await base64(file)}},cleanup:async()=>{}};progress?.('Google ဆီ Video ဖိုင်တင်နေပါတယ်…');const res=await fetch('https://generativelanguage.googleapis.com/upload/v1beta/files',{method:'POST',headers:{'x-goog-api-key':key,'X-Goog-Upload-Protocol':'resumable','X-Goog-Upload-Command':'start','X-Goog-Upload-Header-Content-Length':String(file.size),'X-Goog-Upload-Header-Content-Type':mime(file),'Content-Type':'application/json'},body:JSON.stringify({file:{display_name:file.name||'Future Code Video'}}),signal});if(!res.ok)throw Error('Video upload စတင်မရပါ။ HTTP '+res.status);const uri=res.headers.get('x-goog-upload-url');if(!uri||new URL(uri).origin!=='https://generativelanguage.googleapis.com')throw Error('Google upload address မရပါ။');const put=await fetch(uri,{method:'POST',headers:{'x-goog-api-key':key,'X-Goog-Upload-Offset':'0','X-Goog-Upload-Command':'upload, finalize'},body:file,signal});let f=(await put.json()).file;if(!put.ok||!f?.name)throw Error('Google Video upload မအောင်မြင်ပါ။');const cleanup=()=>api(key,f.name,null,{method:'DELETE',timeout:15000}).catch(()=>{});try{for(let i=0;i<100&&f.state==='PROCESSING';i++){if(signal?.aborted)throw new DOMException('Stopped','AbortError');await sleep(2000);progress?.('Google Video Processing '+(i+1));f=await api(key,f.name,null,{signal})}if(f.state&&f.state!=='ACTIVE')throw Error('Video processing status: '+f.state);return {part:{fileData:{fileUri:f.uri,mimeType:f.mimeType||mime(file)}},cleanup}}catch(e){await cleanup();throw e}}
 async function handoff(blob,details={}){await store('put','handoff','video',{blob,details,at:Date.now()});FCNav.open('editor',{fresh:true})}
 return {$,sleep,status,error,api,parts,text,json,models,base64,mime,imagePart,from64,save,copy,store,voice,audioWav,metadata,videoInput,handoff};
})();
